// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-_6yU9vV_ST_5BUWu4Wz1G3buEACKFY',
    appId: '1:412447033732:web:fa55a0c1c9eaefd80635d1',
    messagingSenderId: '412447033732',
    projectId: 'pneumo-guard',
    authDomain: 'pneumo-guard.firebaseapp.com',
    storageBucket: 'pneumo-guard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq08GBy7J0MBd02H1g-AMgeHnDlFHDi8U',
    appId: '1:412447033732:android:33d10c30a4bb56780635d1',
    messagingSenderId: '412447033732',
    projectId: 'pneumo-guard',
    storageBucket: 'pneumo-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7Bt_Ynxoyo6fcCdsDcfGKCmPQ6W2YFs',
    appId: '1:412447033732:ios:d19afec6cc8f73140635d1',
    messagingSenderId: '412447033732',
    projectId: 'pneumo-guard',
    storageBucket: 'pneumo-guard.appspot.com',
    iosBundleId: 'com.example.pneumoguardapp.pneumoguardapp',
  );
}
